### ISSUE TITLE
iOS 13 compatibility

### ISSUE THREAD

**Issue by m1337v** [danpashin/twackup-rs#11]
Please make this compatible with iOS13.

If the firmware dependency is just due to no test device I'm happy to test.

**Comment by danpashin** [comment]
Not because of test device, actually. iOS 13 misses some important OS API I use in CoreData, UIKit and SwiftUI, so... there won't be iOS 13 and lower support. 

If you're on this versions, you can use [Twackup CLI](https://moreinfo.thebigboss.org/moreinfo/depiction.php?file=twackupDp) which doesn't depend on this frameworks and can run even on iOS 6.
